variables:
  fatsDir: '$(system.defaultWorkingDirectory)/../fats'
  fatsRepo: projectriff/fats
  fatsRefspec: fe05ebb7c2a73889b7f34dc41350bc0115b9cb71 # master as of 2019-06-28

jobs:

- job: stage
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: ./ci/fats-fetch.sh $(fatsDir) $(fatsRefspec) $(fatsRepo)
    displayName: 'Fetch FATS'
  - bash: |
      # $(fatsDir)/install.sh helm
      $(fatsDir)/install.sh gcloud
      # $(fatsDir)/install.sh ytt

      # TODO remove once FATS can install helm
      mkdir helm
      curl -L https://get.helm.sh/helm-v2.14.1-linux-amd64.tar.gz | tar xz -C helm
      chmod +x helm/linux-amd64/helm
      sudo cp helm/linux-amd64/helm /usr/local/bin/
      rm -rf 

      # TODO remove once FATS can install ytt
      curl -L https://github.com/k14s/ytt/releases/download/v0.13.0/ytt-linux-amd64 > ytt
      chmod +x ytt
      sudo mv ytt /usr/local/bin/
    env:
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
    displayName: 'Install tools'
  - bash: |
      helm init --client-only
      make publish-snapshot
    displayName: 'Stage projectriff chart artifacts'
  displayName: 'Stage chart'
