variables:
  fatsDir: '$(system.defaultWorkingDirectory)/../fats'
  fatsRepo: projectriff/fats
  fatsRefspec: ef4811e8d258463151b3d060b14905720cbbd023 # master as of 2019-07-02

jobs:

- job: stage
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: ./ci/fats-fetch.sh $(fatsDir) $(fatsRefspec) $(fatsRepo)
    displayName: 'Fetch FATS'
  - bash: |
      $(fatsDir)/install.sh helm
      $(fatsDir)/install.sh gcloud
      $(fatsDir)/install.sh ytt
    env:
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
    displayName: 'Install tools'
  - bash: |
      helm init --client-only
      make publish-snapshot
    displayName: 'Stage projectriff chart artifacts'
  displayName: 'Stage chart'
