apiVersion: v1
name: projectriff
version: 0.4.0-snapshot
kubeVersion: ^1.11
description: riff is for functions
keywords:
  - projectriff
  - riff
  - faas
home: https://projectriff.io
sources:
  - https://github.com/projectriff
icon: https://projectriff.io/images/riff.png
